# Generated by Django 4.2.5 on 2023-09-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('times', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='times.time')),
            ],
        ),
    ]
